target=	sim_atmega324p_u1
firm_src = ../atmega324p_u1/dist/src
firmware = ../atmega324p_u1/dist/atmega324p_u1.afx
simavr = ../simavr

IPATH = .
#IPATH += ../parts
IPATH += ${simavr}/include
IPATH += ${simavr}/simavr/sim

VPATH = .
#VPATH += ../parts

LDFLAGS += -lpthread

#include ../Makefile.opengl

all: obj ${firmware} ${target}

include ${simavr}/Makefile.common

board = ${OBJ}/${target}.elf

#${board} : ${OBJ}/button.o
${board} : ${OBJ}/${target}.o

${target}: ${board}
	@echo $@ done

clean: clean-${OBJ}
	rm -rf *.a *.axf ${target} *.vcd *.hex
